name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install nlohmann-json
      run: sudo apt update && sudo apt install nlohmann-json-dev
      
    - name: Clean up
      run: make clean
      
    - name: Build
      run: make
